"use client";
import type { AdvisoryResponse } from "@/lib/types";
import { defaults,downloadFile,number,useLocalData } from "@/lib/workspace";
import Link from "next/link";
import { useState } from "react";
import { Empty } from "./DataViews";
const types=['Water Usage','Irrigation','Rainfall','Crop Growth','Weather','Field Activity','Season Summary'];
export default function Reports({data,unit}:{data:AdvisoryResponse;unit:string}){
 const[kind,setKind]=useState('Water Usage');const[from,setFrom]=useState(data.forecast[0]?.date||'');const[to,setTo]=useState(data.forecast.at(-1)?.date||'');const[applied,setApplied]=useState({kind:'Water Usage',from:data.forecast[0]?.date||'',to:data.forecast.at(-1)?.date||''});const[generated,setGenerated]=useState(false);const prefs=useLocalData('muons_preferences',defaults);const journal=useLocalData<any[]>('muons_journal',[]);const factor=unit==='mm'?25.4:1;const tu=prefs.value.temperature==='C'?'C':'F';const temp=(v:number)=>number(tu==='C'?(v-32)*5/9:v,1);const days=data.forecast.filter(d=>(!applied.from||d.date>=applied.from)&&(!applied.to||d.date<=applied.to));let heads:string[],rows:(string|number)[][];let explanation='Forecast estimates, not measured water usage.';
 if(applied.kind==='Field Activity'){heads=['Date','Activity','Notes','Location','Water (as recorded)'];rows=(Array.isArray(journal.value)?journal.value:[]).filter(e=>(!applied.from||e.date>=applied.from)&&(!applied.to||e.date<=applied.to)).map(e=>[e.date,e.category,e.text,e.location||'',e.water||'']);explanation='Browser-local journal entries across all recorded locations. These notes do not update the model.';}
 else if(applied.kind==='Season Summary'){heads=['Crop','Planting date','Accumulated GDD','Progress (%)','Model stage'];rows=[[data.crop.id,data.crop.planting_date||'Unavailable',number(data.crop.cumulative_gdd,0),number(data.crop.gdd_pct,0),data.crop.stage_label||'Unavailable']];explanation='Current season snapshot. The API does not supply full-season historical totals; date filters do not apply to this snapshot.';}
 else if(applied.kind==='Crop Growth'){heads=['Date','GDD','Crop'];rows=days.map(d=>[d.date,number(d.gdd,1),data.crop.id]);explanation='Daily forecast heat units. Current growth is a model estimate, not a measured height.';}
 else if(applied.kind==='Irrigation'){heads=['Date','Model action',`Today’s depth (${unit})`];rows=days.map(d=>[d.date,d.advice_uncertain?'CHECK SOIL':d.action,d.date===data.forecast[0]?.date?(data.today.advice_uncertain||data.soil.water_source==='assumed'?'Check soil':data.today.action==='IRRIGATE'?number(data.today.irrigate_amount*factor,2):'Not advised'):'Not supplied']);explanation='Only the API’s current-day irrigation amount is exported. Future-day doses are not inferred.';}
 else if(applied.kind==='Rainfall'){heads=['Date',`Forecast rain (${unit})`];rows=days.map(d=>[d.date,number(d.precip_in*factor,2)]);explanation='Forecast rainfall only, not a record of observed rain.';}
 else if(applied.kind==='Weather'){heads=['Date',`High (°${tu})`,`Low (°${tu})`,`Rain (${unit})`,`Reference ET (${unit})`];rows=days.map(d=>[d.date,temp(d.tmax_f),temp(d.tmin_f),number(d.precip_in*factor,2),number(d.et0_in*factor,2)]);explanation='Daily weather forecast from the current advisory response.';}
 else {heads=['Date',`Crop water use (${unit})`,`Rain (${unit})`,`Model soil water (${unit})`];rows=days.map(d=>[d.date,number(d.etc*factor,2),number(d.precip_in*factor,2),number(d.soil_water*factor,2)]);}
 const invalid=!!from&&!!to&&from>to;
 function csv(){const esc=(v:unknown)=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};downloadFile(`muons-${data.county.fips}-${applied.kind.toLowerCase().replaceAll(' ','-')}.csv`,[heads,...rows].map(r=>r.map(esc).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
 return <><div className="mw-banner">Reports contain available model data or your browser-local field records. They are not field-validation certificates.</div><form className="mw-card mb-6 mw-no-print" onSubmit={e=>{e.preventDefault();if(!invalid){setApplied({kind,from,to});setGenerated(true);}}}><h2>Build a field report</h2><div className="mw-report-filters"><label className="mw-field">Field / county<input readOnly value={`${data.county.name}, ${data.county.state}`}/><Link href="/dashboard" className="mw-field-hint underline">Change active field in Overview</Link></label><label className="mw-field">Crop<input readOnly value={data.crop.id}/></label><label className="mw-field">Report type<select value={kind} onChange={e=>setKind(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="mw-field">From date<input type="date" disabled={kind==='Season Summary'} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="mw-field">To date<input type="date" disabled={kind==='Season Summary'} value={to} onChange={e=>setTo(e.target.value)}/></label></div>{invalid&&<p role="alert" className="mw-form-status error">End date must be on or after start date.</p>}<div className="mw-row"><button className="mw-btn" disabled={invalid}>Generate Report</button><button type="button" className="mw-btn secondary" disabled={!rows.length} onClick={csv}>Export CSV</button><button type="button" className="mw-btn secondary" onClick={()=>window.print()}>Export PDF</button></div><p className="mw-note">Exports use the preview below. For PDF, choose Save as PDF in the browser print dialog.</p>{generated&&<p role="status" className="mw-form-status">Report preview generated.</p>}</form><section className="mw-card"><h2>{applied.kind} report preview</h2><p>{data.county.name}, {data.county.state} · {data.crop.id} · {unit} · {applied.from||'All dates'} to {applied.to||'latest'}</p><p className="mw-note">{explanation}</p>{rows.length?<div className="mw-table-wrap"><table className="mw-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td className="max-w-sm !whitespace-normal break-words" key={j}>{v}</td>)}</tr>)}</tbody></table></div>:<Empty title="No records in this range" body="Choose another date range or report type. No values have been estimated to fill the gap."/>}<p className="mw-note">Last pipeline: {data.data_as_of?.last_pipeline_at||'Unavailable'}. Soil initialization bounds exclude weather and model error.</p></section></>;
}
